---
version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: docker-username
    DOCKER_PASSWORD: docker-password

phases:
  pre_build:
    commands:
      - echo Installing boto3...
      - pip install boto3
      - echo Fetching Build Counter...
      - export BUILD_COUNTER=$(python build-number.py $CODEBUILD_BUILD_ARN)
      - echo Build $BUILD_COUNTER
      - echo Logging into Docker Hub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

  build:
    commands:
      - echo Build starting on `date`
      - echo Build the docker image...
      - docker build . -t $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:build-$BUILD_COUNTER

  post_build:
    commands:
      - echo Build complete on `date`
      - echo Pushing build to Docker Hub...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing build-$BUILD_COUNTER tag to Docker Hub...
      - docker push $IMAGE_REPO_NAME:build-$BUILD_COUNTER
      - echo Notifying myself of this build...
      - python build-notify.py $IMAGE_REPO_NAME:build-$BUILD_COUNTER
