---
name: Build/Deploy
env:
  IMAGE_REPO_NAME: zostay/postfix
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_REPO_NAME }}
    - uses: docker-push-build@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
