---
name: Build/Deploy
env:
  IMAGE_REPO_NAME: zostay/postfix
on:
  push:
    branches: [ master ]

  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: aws-action/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - uses: action/setup-python@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v2
    - name: Install boto3
      run: pip install boto3
    - name: Update Build Number
      env:
        BUILD_TAG: ${{ secrets.BUILD_TAG }}
      run: "::set-env name=BUILD_COUNTER::$(python build-number.py $BUILD_TAG)"
    - run: "echo Build $BUILD_COUNTER"
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_REPO_NAME }}:latest,${{ env.IMAGE_REPO_NAME }}:build-${{ env.BUILD_NUMBER }}
    - run: "python build-notify.py $IMAGE_RPO_NAME:build-$BUILD_COUNTER"
